# A sample Gemfile
source "https://rubygems.org"
gem 'json','1.8.3'
gem 'cucumber', '2.3.3'
gem 'data_magic', '0.22'
gem 'fig_newton','0.12'
gem 'pretty_face', '0.10.3'
gem 'random_data','1.6.0'
gem 'rspec', '3.4.0'
gem 'rspec-expectations'
gem 'selenium-webdriver', '2.52.0'
gem 'syntax','1.2.0'
gem 'require_all','1.3.3'
gem 'logging','2.0.0'
gem 'parallel','1.6.1'
gem 'parallel_tests','2.3.1'
gem 'money','6.7.0'
gem 'rest-client','1.8.0'
gem 'chromedriver-helper'
gem 'teamcity_formatter'
