class CartSummaryRowItem < PageObject
    @thumbnail = WebElement.new({:css => ".CartSummary-cartProductImage"})
    @item_name = WebElement.new({:css => ".CartSummary-descriptionContainer>div:nth-child(2)"})
    @item_desc = WebElement.new({:css => ".CartSummary-descriptionContainer>div:nth-child(3)"})
    @compliant = WebElement.new({:css => ".CartSummary-rohs"})
    @ship_date = WebElement.new({:css => ".CartSummary-shipDateContainer"})
    @ships_from = WebElement.new({:css => ".CartSummary-shipDateContainer>div:nth-child(1)"})
    @est_ship = WebElement.new({:css => ".CartSummary-shipDateContainer>div:nth-child(2)"})
    @item_price = WebElement.new({:css => ".CartSummary-priceContainer>div:nth-child(1)"})
    @item_total = WebElement.new({:css => ".CartSummary-priceContainer>div:nth-child(2)"})
    @pencil = WebElement.new({:css => ".Icon--edit"})
    @trash_can = WebElement.new(".CartSummary-removeItem")
    @item_quantity = WebElement.new({:css => ".CartSummary-updateQuantity"})
    @item_cpn = WebElement.new({:css => ".CartSummary-quantityContainer>div:nth-child(2)"})
    @item_mpn = WebElement.new({:css => ".CartSummary-catalogPart"})
end