base_url: https://scordutility1.arwcloud.net
cart_url: https://cart.arrow.com
components_url: http://components.arrow.com

sitecore_username: biomonitor
sitecore_password: S2o7Ua7z8T144Uc

sitecore_user1: Automation1
sitecore_user2: Automation2
sitecore_user3: Automation3
sitecore_user4: Automation4
sitecore_pass: LsAy_9b&