base_url: https://lon.arrow.com
cart_url: https://cart.arrow.com
components_url: http://components.arrow.com
webinar_detail_url: research-and-events/events/webinar-serial-nor-flash-the-all-purpose-flash-memory

sitecore_username: biomonitor
sitecore_password: S2o7Ua7z8T144Uc

sitecore_user1: Automation1
sitecore_user2: Automation2
sitecore_user3: Automation3
sitecore_user4: Automation4
sitecore_pass: LsAy_9b&

# Login splash myArrowUser

myArrowUsername: Donaldpmeyer@gmail.com
myArrowUserPassword: Arrow123
myArrowUsertext : Don Meyer

# components page

components_arrow_page_url: http://components.arrow.com/part/search/1?

#region url
region_url: http://components.arrow.com/part/search/1?region=


#login splash page url
login_splash_page_url : /login-splash?url=https%3A%2F%2Flon.arrow.com%2Fen%2Flogin%3Furl%3D