base_url: https://www.arrow.com
cart_url: https://cart.arrow.com
components_url: http://components.arrow.com

rr_base_url: //recs

sitecore_username: biomonitor
sitecore_password: S2o7Ua7z8T144Uc

sitecore_user1: Automation1
sitecore_user2: Automation2
sitecore_user3: Automation3
sitecore_user4: Automation4
sitecore_pass: LsAy_9b&
time: 30
impl_timeout: 10

username: autotest1@mailinator.com
password: asdf1234

home_page_title: Arrow.com

# Login splash myArrowUser

myArrowUsername: Donaldpmeyer@gmail.com
myArrowUserPassword: Arrow123
myArrowUsertext : Don Meyer

# components page

components_arrow_page_url: http://components.arrow.com/part/search/1?

#region url
region_url: http://components.arrow.com/part/search/1?region=


#login splash page url
login_splash_page_url : /login-splash?url=https%3A%2F%2F.arrow.com%2Fen%2Flogin%3Furl%3D
#--------------------------------------------------------------------------

# cairo site map search page

cairo_sitemap_search_page_url : http://172.17.80.119/SearchWS/sitemap.xml



#Content Page Data:
news_article_title: Stop! Shunt Regulators Help Your Car Come to a Halt
video_article_url: research-and-events/videos/te-sensors-for-smarter-more-connected-creations
event_detail_url: research-and-events/articles/impacting-our-energy-levels-with-light
webinar_detail_url: research-and-events/events/webinar-serial-nor-flash-the-all-purpose-flash-memory

reference_design_lists_title: Featured reference designs
recently_viewed_title: Recently viewed
featured_datasheet_title: Featured datasheets
featured_datasheet_title_new_users: Recommended Datasheets
div_landing_page: divisions/enterprise-computing-solutions
faq_page: support/contact-support/faqs
contact_us_page: support/contact-support/contact-arrow
#--------------------------------------------------------------------------
#Reference Design Data:

ref_design_with_no_assoc_doc_id: 3758A6CC65FA5A37ADC7BF34FDCD923E
ref_design_with_no_assoc_doc_url_param: abx8xx-i2c-evk-evaluation-kit-to-assess-the-complete-feature-set-in-the-ultra-low-power-product/

ref_design_with_5_related_id: BABAEC8B4C2F2D20E5CBCCF73544D4B7
ref_design_with_5_related_url_param: lm9061evm-high-side-protection-controller-evaluation-module/

datasheet_standard_search_string: BAV

datasheet_without_family_id: 41691808
datasheet_without_family_for: MS27497T10A99SA, MS27497T10F35SD, MS27497T12A22P

datsheet_with_less_than_three_id: 49376613
datsheet_with_less_than_three_for: BAW56L, SBAW56L

datsheet_with_more_than_three_id: 119043987
datsheet_with_more_than_three_for: SAMD20E16A, ATSAMD20E15A, SAMD20G15A
no_datasheet_found_en_msg: Datasheet - preview is not currently available

product_category_with_non_numeric_filter: "Active+Filter"

wide_search: 'diode'

product_for_purchase: BAV170T-7-F
#--------------------------------------------------------------------------
default_column_layout: PART NO. PRICE STOCK MANUFACTURER TYPE DESCRIPTION

engineer_email_form:
  :name: BB King
  :email: kingsman@example.com
  :company: Big Strut Engineering
  :city: Nova Zeland
  :state: Ohiado
  :question: Does it come in blue?