base_url: https://uat.cms.arrow.com
cart_url: https://cart.arrow.com
rr_base_url: //integration
components_url: http://components.arrow.com


sitecore_username: admin
sitecore_password: b

sitecore_user1: Automation1
sitecore_user2: Automation2
sitecore_user3: Automation3
sitecore_user4: Automation4
sitecore_pass: LsAy_9b&

time: 30
impl_timeout: 10

username: autotest1@mailinator.com
password: asdf1234

cairo_healthcheck_user_name: quality
cairo_healthcheck_user_password: 123456

home_page_title: Arrow.com

# components page

components_arrow_page_url: http://components.arrow.com/part/search/1?

#login splash page url
login_splash_page_url : /login-splash?url=https%3A%2F%2Fuat.arrow.com%2Fen%2Flogin%3Furl%3D
#--------------------------------------------------------------------------
#Config/Data for tests to be run on QA ONLY:
cairo_healthcheck_user_name: quality
cairo_healthcheck_user_password: 123456

sales_person_page: sales/demo-sales-person
#--------------------------------------------------------------------------
#Content Page Data:
news_article_url: research-and-events/articles/mixed-results-for-memory-in-2014-and-2015
news_article_title: Mixed Results for Memory in 2014 and 2015
video_article_url: research-and-events/videos/five-year-olds-five-years-out-transportation-master
event_detail_url: research-and-events/articles/using-the-iot-to-predict-heart-attacks-and-cancer

webinar_detail_url: research-and-events/events/webinar-serial-nor-flash-the-all-purpose-flash-memory

reference_design_lists_title: Featured datasheets
recently_viewed_title: Recently viewed
featured_datasheet_title: Featured datasheets
featured_datasheet_title_new_users: Recommended Datasheets

#div_landing_page: divisions/computing-solutions

faq_page: support/contact-support/faqs
contact_us_page: support/contact-support/contact-arrow
#--------------------------------------------------------------------------
#Reference Design Data:

ref_design_with_no_assoc_doc_id: 71728030D77EFED5BA3E8FE14298C4BA
ref_design_with_no_assoc_doc_url_param: iceblink40-lp1k-evaluation-kit

ref_design_with_5_related_id: 3B5D465D293F81F1BED3D799B36461DC
ref_design_with_5_related_url_param: eval-adf4158eb1z-evaluation-board-for-fractional-n-pll-frequency-synthesizer

wide_search: 'diode'

product_for_purchase: ISC01P
#--------------------------------------------------------------------------
#DATASHEETS Data:
datasheets_id: 82708719
datasheet_for: BZT52B15LP

datasheet_standard_search_string: BAV

datasheet_without_family_id: 41691808
datasheet_without_family_for: MS27473E16F35P, MS27497E24F35SC, MS27513E10A5

datsheet_with_less_than_three_id: 69690362
datsheet_with_less_than_three_for: ADP2301, ADP2300

datsheet_with_more_than_three_id: 37469902
datsheet_with_more_than_three_for: DDZ11ASF, DDZ4V7BSF, DDZ3V3ASF
no_datasheet_found_en_msg: Datasheet - preview is not currently available

product_category_with_non_numeric_filter: "Active+Filter"

#--------------------------------------------------------------------------
default_column_layout: PART NO. PRICE STOCK MANUFACTURER TYPE DESCRIPTION

engineer_email_form:
  :name: BB King
  :email: kingsman@example.com
  :company: Big Strut Engineering
  :city: Nova Zeland
  :state: Ohiado
  :question: Does it come in blue?